# Generated by Django 2.1.3 on 2018-11-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('raza', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='fotos')),
                ('adoptado', models.BooleanField(default=False)),
                ('adoptante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adopcion.Adoptante')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='tipo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mascota.Tipo'),
        ),
    ]
